### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by navierula** [grolimur/dvp-u3-constellations#1]
**File Format and Libraries (4/4)**
The file is saved as a Jupyter Notebook, and all necessary libraries are imported.

**Implementation of 2D visualization (3/4)**
The 2D grid appears with data plotted on the graph. The visualization includes a customized style and a title; however, does not have labels for the x-axis and y-axis.

**Implementation of 3D visualization (3/4)**
The 3D grid appears with the correct data plotted on the graph. The grid is rotatable. The visualization includes a customized style and a title; however, does not have labels for the x-axis and y-axis.

---

Great job on this project! I'd emphasize more creativity in your visualizations, especially in terms or color/styling. I liked that you changed the symbols in the 2D visualization. Keep in mind that your audience may not be as familiar with your visualizations as you are, so be sure to always label everything thoroughly as well.

**Comment by grolimur** [comment]
Thanks for your feedback, @navierula !
I'll keep in mind to make my graphs as clear as possible and therefore use labels.
